shopping_pairproject_01/shop_manager/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'shop_manager'
urlpatterns = [
    path('', views.index, name='index'),
    path('add_shop', views.add_shop, name='add_shop'),
    path('delete_shop/<int:shop_id>', views.delete_shop, name='delete_shop'),
    path('shopping_list_detail/<int:list_id>', views.shopping_list_detail, name='shopping_list_detail'),
    path('add_shopping_list', views.add_shopping_list, name='add_shopping_list'),
    path('delete_shopping_list/<int:list_id>', views.delete_shopping_list, name='delete_shopping_list'),
    path('add_item/<int:list_id>', views.add_item, name='add_item'),
    path('delete_item/<int:list_id>/<int:item_id>', views.delete_item, name='delete_item'),
    path('change_status/<int:list_id>/<int:item_id>', views.change_status, name='change_status'),
    path('shop_detail/<int:shop_id>', views.shop_detail, name='shop_detail'),
]




shopping_pairproject_01/shopping_pairproject_01/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop_manager/', include('shop_manager.urls'))
]

shopping_pairproject_01/shop_manager/models.py
from django.db import models
import datetime
from datetime import date
#from django.utils.timezone import now
# Create your models here.

item_type = [
    ('L', 'Liter'),
    ('KG', 'Kilogramm'),
    ('S', 'Stückzahl'),
]



class Item(models.Model):
    item_name = models.CharField(max_length=50)
    status = models.BooleanField(default = False)
    amount_float = models.FloatField(default=1)
    amount_type = models.CharField(max_length=2, choices=item_type, default="S")
    shop = models.ForeignKey(to="Shop", on_delete=models.CASCADE)
    #list = models.ForeignKey(to="Shopping_list", on_delete=models.SET_NULL, null=True)
    list = models.ForeignKey(to="Shopping_list", on_delete=models.CASCADE, default=1)
    

    def type_translation(self):
        type_text = {
            "L": "Liter",
            "KG": "Kilogramm",
            "S": "Stückzahl",
        }
        return type_text[self.amount_type]
    
    def __str__(self):
        return f'{self.item_name} {self.amount_type[0]}'



class Shop(models.Model):
    shop_name = models.CharField(max_length=50)
    opening_hours = models.CharField(max_length=50)

    def __str__(self):
        return self.shop_name


class Shopping_list(models.Model):
    list_name = models.CharField(max_length=50, default= "shop")
    shopping_date = models.DateField(auto_now_add=False, auto_now=False, default=date.today)
    list_date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.list_name

shopping_pairproject_01/shop_manager/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from .models import Shop, Item, Shopping_list
from django.urls import reverse
# Create your views here.

def index(request):
    context = {}
    context["shopping_lists"]=Shopping_list.objects.all()
    context["shops"]=Shop.objects.all()
    return render(request, "shop_manager/index.html", context)


def add_shop(request):
    if "shop_name" in request.POST:
        shop = Shop()
        shop.shop_name = request.POST["shop_name"]
        shop.opening_hours = request.POST["opening_hours"]
        shop.save()
    return redirect("shop_manager:index")

def delete_shop(request, shop_id):
    shop = Shop.objects.get(pk=shop_id)
    shop.delete()
    return redirect("shop_manager:index")


def shopping_list_detail(request, list_id):
    context = {}
    context["items"]=Item.objects.filter(list=list_id)
    context["shopping_list"]=Shopping_list.objects.get(pk=list_id)
    context["shops"]=Shop.objects.all()
    return render(request, "shop_manager/shopping_list_detail.html", context)

def add_shopping_list(request):
    if "list_name" in request.POST:
        shopping_list = Shopping_list()
        shopping_list.list_name = request.POST["list_name"]
        shopping_list.shopping_date = request.POST["shopping_date"]
        shopping_list.save()
    return redirect("shop_manager:index")

def delete_shopping_list(request, list_id):
    shopping_list = Shopping_list.objects.get(pk=list_id)
    shopping_list.delete()
    return redirect("shop_manager:index")

def add_item(request, list_id):
    list = Shopping_list.objects.get(pk=list_id)
    if "item_name" in request.POST:
        item = Item()
        item.item_name = request.POST["item_name"]
        item.amount_float = request.POST["amount_float"]
        item.amount_type = request.POST["amount_type"]
        item.shop = Shop.objects.get(pk=request.POST["shop_name"])
        item.list = Shopping_list.objects.get(pk=list_id)
        item.save()
    return HttpResponseRedirect(reverse("shop_manager:shopping_list_detail", args=(list.id,)))

def delete_item(request, item_id, list_id):
    list = Shopping_list.objects.get(pk=list_id)
    item = Item.objects.get(pk=item_id)
    item.delete()
    return HttpResponseRedirect(reverse("shop_manager:shopping_list_detail", args=(list.id,)))

def change_status(request, item_id, list_id):
    list = Shopping_list.objects.get(pk=list_id)
    item = Item.objects.get(pk=item_id)
    item.status = True
    item.save()
    return HttpResponseRedirect(reverse("shop_manager:shopping_list_detail", args=(list.id,)))


def shop_detail(request, shop_id):
    context = {}
    context["items"]=Item.objects.filter(shop=shop_id)
    context["shops"]=Shop.objects.get(pk=shop_id)
    return render(request, "shop_manager/shop_detail.html", context)

shopping_pairproject_01/shop_manager/templates/shop_manager/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <title>{% block title %}No Title{% endblock title %}</title>
</head>

<body class="bg-primary">
    <div class="container my-3 mx-auto py-3 bg-white">
        {% block content %}

        {% endblock %}
    </div>
</body>

</html>

shopping_pairproject_01/shop_manager/templates/shop_manager/index.html
{% extends 'shop_manager/base.html' %}
{% block title %}Startseite{% endblock title %}

{% block content %}
<div class="container">
    <div class="row text-center">
        <h1>Die Coolste Einkaufsliste</h1>
    </div>
    <div class="row">
        <div class="col">

            <div class="container">
                <h3>Shop Liste</h3>
                <ul>
                    {% for shop in shops %}
                    <li><a href="{% url 'shop_manager:shop_detail' shop.id %}">{{shop.shop_name}}</a>
                        {{shop.opening_hours}} {{shop.id}}
                        <a class="btn btn-secondary" href="{% url 'shop_manager:delete_shop' shop.id %}">Delete</a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="col">
            <div class="container">
                <table class="table table-striped table-sm">
                    <th>Einkaufsliste</th>
                    <th>Angebotsdatum</th>
                    <th>Entfernen</th>
                    {% for list in shopping_lists %}
                    <tr>
                        <td><a href="{% url 'shop_manager:shopping_list_detail' list.id %}">{{list.list_name}}</a></td>
                        <td>{{list.shopping_date}}</td>
                        <td><a class="btn btn-secondary" href="{% url 'shop_manager:delete_shopping_list' list.id %}">Delete</a></td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="container">
                <form action="{% url 'shop_manager:add_shop' %}" method="post">
                    {% csrf_token %}
                    <div class="input-group">
                    <input type="text" name="shop_name" placeholder="shop">
                    <input type="text" name="opening_hours" placeholder="XX:XX-XX:XX">
                    <input class="btn btn-primary" type="submit" value="add_shop">
                    </div>
                </form>
            </div>
        </div>
        <div class="col">
            <div class="container">
                <form action="{% url 'shop_manager:add_shopping_list' %}" method="post">
                    {% csrf_token %}
                    <div class="input-group">
                    <select class="form-select" name="list_name">
                        {% for shop in shops %}
                        <option value="{{shop.shop_name}}">{{shop.shop_name}}</option>
                        {% endfor %}
                    </select>
                    <input type="date" name="shopping_date">
                    <input class="btn btn-primary" type="submit" value="add_shopping_list">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

shopping_pairproject_01/shop_manager/templates/shop_manager/shop_detail.html
{% extends 'shop_manager/base.html' %}
{% block title %}{{shop.shop_name}}{% endblock title %}
{% block content %}

<div class="container">
    <table class="table table-striped table-sm">
        <th>Item Name</th>
        <th>Zugewiesener Laden</th>
        <th>Innerhalb Liste</th>
        {% for item in items %}
        <tr>
            <td>{{item.item_name}}</td>
            <td>{{item.shop}}</td>
            <td>{{item.list}}</td>
        </tr>
        {% endfor %}
    </table>
</div>
<div class="container">
    <a class="btn btn-secondary" href="{% url 'shop_manager:index' %}">Return to Index</a>
</div>
{% endblock %}

shopping_pairproject_01/shop_manager/templates/shop_manager/shopping_list_detail.html
{% extends 'shop_manager/base.html' %}
{% block title %}{{shopping_list.list_name}}{% endblock title %}
{% block content %}
<div class="container">
    <table class="table table-striped table-sm">
        <th>Item Name</th>
        <th>Item status</th>
        <th>Item amount</th>
        <th>Item type</th>
        <th></th>
        <th></th>
        {% if items %}
        {% for item in items %}
        <tr>
            <td>{{item.item_name}}</td>
            <td>{{item.status}}</td>
            <td>{{item.amount_float}}</td>
            <td>{{item.type_translation}}</td>
            <td><a class="btn btn-secondary"
                    href="{% url 'shop_manager:delete_item' shopping_list.id item.id %}">Delete</a></td>
            <td><a class="btn btn-secondary"
                    href="{% url 'shop_manager:change_status' shopping_list.id item.id %}">Gekauft</a></td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td>Hier könnte ein Item stehen</td>
            <td>Hier wäre der Status</td>
            <td>Menge</td>
            <td>Typ</td>
        </tr>
        {% endif %}
    </table>
</div>
<div class="container">
    <form action="{% url 'shop_manager:add_item' shopping_list.id %}" method="post">
        {% csrf_token %}
        <div class="input-group mb-1">
        <input type="text" name="item_name" placeholder="item">
        <input type="text" name="amount_float" placeholder="put in amount">
        <select class="form-select" name="amount_type">
            <option value="L">Liter</option>
            <option value="KG">Kilogramm</option>
            <option value="S">Stückzahl</option>
        </select>
        <select class="form-select" name="shop_name">
            {% for shop in shops %}
            <option value="{{shop.id}}">{{shop.shop_name}}</option>
            {% endfor %}
        </select>
        <input class="btn btn-primary" type="submit" value="add_item">
        </div>
    </form>
</div>
<div class="container">
    <a class="btn btn-secondary" href="{% url 'shop_manager:index' %}">Return to Index</a>
</div>
{% endblock %}